# Generated by Django 4.2.16 on 2024-12-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_task_user'),
        ),
    ]
